from sqlalchemy import Column, Integer, String, Float, JSON
from database import Base

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)

class Prediction(Base):
    __tablename__ = "predictions"
    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, index=True)
    at_risk_prediction = Column(Integer)
    risk_probability = Column(Float)
    
    # We use JSON columns to easily store the arrays generated by our ML service
    top_risk_factors = Column(JSON)
    recommended_interventions = Column(JSON)